-- The Tipssy Toe Makeover Studio - Supabase schema
-- Run this once in Supabase SQL Editor.

create table if not exists public.services (
  id bigint generated by default as identity primary key,
  source_id text unique,
  name text not null,
  price numeric(12,2) not null check (price > 0),
  status text not null default 'Active' check (status in ('Active','Inactive')),
  created_at timestamptz not null default now()
);

create table if not exists public.combos (
  id bigint generated by default as identity primary key,
  source_id text unique,
  name text not null,
  price numeric(12,2) not null check (price > 0),
  services jsonb not null default '[]'::jsonb,
  includes text,
  created_at timestamptz not null default now()
);

create table if not exists public.appointments (
  id bigint generated by default as identity primary key,
  source_id text unique,
  name text not null,
  phone text not null,
  email text,
  service text not null,
  date date not null,
  time text not null,
  status text not null default 'Pending' check (status in ('Pending','Confirmed','Completed','Cancelled')),
  created_at timestamptz not null default now()
);

create table if not exists public.customer_bills (
  id bigint generated by default as identity primary key,
  source_id text unique,
  bill_date text not null,
  name text not null,
  mobile text not null,
  items jsonb not null default '[]'::jsonb,
  subtotal numeric(12,2) not null default 0,
  discount numeric(12,2) not null default 0,
  payment text,
  total numeric(12,2) not null default 0,
  created_at timestamptz not null default now()
);

alter table public.services enable row level security;
alter table public.combos enable row level security;
alter table public.appointments enable row level security;
alter table public.customer_bills enable row level security;

-- Public catalogue: customers need to read active services/combos.
drop policy if exists "public read services" on public.services;
create policy "public read services" on public.services for select to anon, authenticated using (true);

drop policy if exists "public read combos" on public.combos;
create policy "public read combos" on public.combos for select to anon, authenticated using (true);

-- Booking page needs to create appointments.
drop policy if exists "public create appointments" on public.appointments;
create policy "public create appointments" on public.appointments for insert to anon, authenticated with check (true);

-- Admin pages currently use the existing client-side login. These policies make the
-- current static site functional; for production security, move admin login to Supabase Auth.
drop policy if exists "site read appointments" on public.appointments;
create policy "site read appointments" on public.appointments for select to anon, authenticated using (true);
drop policy if exists "site update appointments" on public.appointments;
create policy "site update appointments" on public.appointments for update to anon, authenticated using (true) with check (true);
drop policy if exists "site delete appointments" on public.appointments;
create policy "site delete appointments" on public.appointments for delete to anon, authenticated using (true);

drop policy if exists "site manage services" on public.services;
create policy "site insert services" on public.services for insert to anon, authenticated with check (true);
create policy "site update services" on public.services for update to anon, authenticated using (true) with check (true);
create policy "site delete services" on public.services for delete to anon, authenticated using (true);

drop policy if exists "site manage combos" on public.combos;
create policy "site insert combos" on public.combos for insert to anon, authenticated with check (true);
create policy "site update combos" on public.combos for update to anon, authenticated using (true) with check (true);
create policy "site delete combos" on public.combos for delete to anon, authenticated using (true);

drop policy if exists "site manage bills" on public.customer_bills;
create policy "site read bills" on public.customer_bills for select to anon, authenticated using (true);
create policy "site insert bills" on public.customer_bills for insert to anon, authenticated with check (true);
create policy "site delete bills" on public.customer_bills for delete to anon, authenticated using (true);

-- Prevent accidental exposure of future tables by Data API grants; review in Dashboard too.
